trigger:
  branches:
    include:
      - main

pool:
  name: 'Default'
  demands:
    - Jay Aguilar

steps:
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '8.x'  
      installationPath: $(Agent.ToolsDirectory)/dotnet

  - task: Restore@2
    inputs:
      command: 'restore'
      projects: '**/*.csproj'

  - task: Build@1
    inputs:
      projects: '**/*.csproj'

  - task: Publish@1
    inputs:
      publishWebProjects: true
      arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)'
      zipAfterPublish: true

artifacts:
  - artifact: drop
    type: pipeline
    name: $(Build.DefinitionName)_$(Build.BuildId)
    path: $(Build.ArtifactStagingDirectory)
