trigger:
  branches:
    include:
      - main  # Trigger the pipeline on commits to the 'main' branch

pool:
  name: 'Default'  # This is the pool for the self-hosted agent
  demands:
    - agent.name -equals your-self-hosted-agent-name  # Replace with your agent name

steps:
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '5.x'  # Update to the version of .NET you are using
      installationPath: $(Agent.ToolsDirectory)/dotnet

  - task: Restore@2
    inputs:
      command: 'restore'
      projects: '**/*.csproj'

  - task: Build@1
    inputs:
      projects: '**/*.csproj'

  - task: Publish@1
    inputs:
      publishWebProjects: true
      arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)'
      zipAfterPublish: true

# This will output the build artifact
artifacts:
  - artifact: drop
    type: pipeline
    name: $(Build.DefinitionName)_$(Build.BuildId)
    path: $(Build.ArtifactStagingDirectory)
