trigger:
  branches:
    include:
      - main  # or master

pool:
  name: 'Default'
  demands:
    - agent.os -equals Windows_NT

steps:
- task: UseDotNet@2
  displayName: 'Use .NET 8 SDK'
  inputs:
    packageType: 'sdk'
    version: '8.x.x'

- task: Restore@2
  displayName: 'Restore NuGet packages'
  inputs:
    restoreSolution: '**/*.sln'

- task: Build@1
  displayName: 'Build solution'
  inputs:
    solution: '**/*.sln'
    clean: true
    restore: true
    buildPlatform: 'Any CPU'
    buildConfiguration: 'Release'

- task: NuGetCommand@2
  displayName: 'Pack NuGet package'
  inputs:
    command: 'pack'
    packagesToPack: '**/*.csproj'
    versioningScheme: 'off'
    outputDir: '$(Build.ArtifactStagingDirectory)'

- task: NuGetCommand@2
  displayName: 'Push NuGet package'
  inputs:
    command: 'push'
    publishVstsFeed: 'COMP367Lab4JAguilar'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    allowPackageConflicts: true

